require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exercise_per_weeks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExercisePerWeek. As you add validations to ExercisePerWeek, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExercisePerWeek.create! valid_attributes
      get exercise_per_weeks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      exercise_per_week = ExercisePerWeek.create! valid_attributes
      get exercise_per_week_url(exercise_per_week)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exercise_per_week_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      exercise_per_week = ExercisePerWeek.create! valid_attributes
      get edit_exercise_per_week_url(exercise_per_week)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExercisePerWeek" do
        expect {
          post exercise_per_weeks_url, params: { exercise_per_week: valid_attributes }
        }.to change(ExercisePerWeek, :count).by(1)
      end

      it "redirects to the created exercise_per_week" do
        post exercise_per_weeks_url, params: { exercise_per_week: valid_attributes }
        expect(response).to redirect_to(exercise_per_week_url(ExercisePerWeek.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExercisePerWeek" do
        expect {
          post exercise_per_weeks_url, params: { exercise_per_week: invalid_attributes }
        }.to change(ExercisePerWeek, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exercise_per_weeks_url, params: { exercise_per_week: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exercise_per_week" do
        exercise_per_week = ExercisePerWeek.create! valid_attributes
        patch exercise_per_week_url(exercise_per_week), params: { exercise_per_week: new_attributes }
        exercise_per_week.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the exercise_per_week" do
        exercise_per_week = ExercisePerWeek.create! valid_attributes
        patch exercise_per_week_url(exercise_per_week), params: { exercise_per_week: new_attributes }
        exercise_per_week.reload
        expect(response).to redirect_to(exercise_per_week_url(exercise_per_week))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        exercise_per_week = ExercisePerWeek.create! valid_attributes
        patch exercise_per_week_url(exercise_per_week), params: { exercise_per_week: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested exercise_per_week" do
      exercise_per_week = ExercisePerWeek.create! valid_attributes
      expect {
        delete exercise_per_week_url(exercise_per_week)
      }.to change(ExercisePerWeek, :count).by(-1)
    end

    it "redirects to the exercise_per_weeks list" do
      exercise_per_week = ExercisePerWeek.create! valid_attributes
      delete exercise_per_week_url(exercise_per_week)
      expect(response).to redirect_to(exercise_per_weeks_url)
    end
  end
end
