require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/habits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Habit. As you add validations to Habit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Habit.create! valid_attributes
      get habits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      habit = Habit.create! valid_attributes
      get habit_url(habit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_habit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      habit = Habit.create! valid_attributes
      get edit_habit_url(habit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Habit" do
        expect {
          post habits_url, params: { habit: valid_attributes }
        }.to change(Habit, :count).by(1)
      end

      it "redirects to the created habit" do
        post habits_url, params: { habit: valid_attributes }
        expect(response).to redirect_to(habit_url(Habit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Habit" do
        expect {
          post habits_url, params: { habit: invalid_attributes }
        }.to change(Habit, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post habits_url, params: { habit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested habit" do
        habit = Habit.create! valid_attributes
        patch habit_url(habit), params: { habit: new_attributes }
        habit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the habit" do
        habit = Habit.create! valid_attributes
        patch habit_url(habit), params: { habit: new_attributes }
        habit.reload
        expect(response).to redirect_to(habit_url(habit))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        habit = Habit.create! valid_attributes
        patch habit_url(habit), params: { habit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested habit" do
      habit = Habit.create! valid_attributes
      expect {
        delete habit_url(habit)
      }.to change(Habit, :count).by(-1)
    end

    it "redirects to the habits list" do
      habit = Habit.create! valid_attributes
      delete habit_url(habit)
      expect(response).to redirect_to(habits_url)
    end
  end
end
